spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari.maxLifeTime: 60000
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog\changelog-master.xml
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  jackson.serialization-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server.port: ${PORT:8080}